//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TPLedit.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TPLEDIT_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     130
#define IDD_NEWMATERIAL                 131
#define IDD_NEWLIGHT                    132
#define IDD_NEWCAMERA                   133
#define IDD_NEWRAW                      134
#define IDD_EDITVI                      135
#define IDD_SUBSETMANAGER               136
#define IDD_DIALOG2                     137
#define IDD_DIALOG3                     138
#define IDC_PATH                        1000
#define IDC_BUTTON1                     1001
#define IDC_BUTTON2                     1002
#define IDC_BUTTON3                     1003
#define IDC_VERSION                     1004
#define IDC_SIGNATURE                   1005
#define IDC_BUTTON5                     1005
#define IDC_DESCRIPTION                 1006
#define IDC_BUTTON15                    1006
#define IDC_COMMENTS                    1007
#define IDC_BUTTON16                    1007
#define IDC_BUTTON4                     1008
#define IDC_BUTTON6                     1009
#define IDC_BUTTON7                     1010
#define IDC_BUTTON8                     1011
#define IDC_BUTTON10                    1012
#define IDC_BUTTON11                    1013
#define IDC_BUTTON9                     1014
#define IDC_HEADEROFFS                  1015
#define IDC_BUTTON12                    1015
#define IDC_HEADERSIZE                  1016
#define IDC_UID                         1017
#define IDC_GUID                        1018
#define IDC_COMPRESSION                 1019
#define IDC_COMPRESSIZE                 1020
#define IDC_ORIGINALSIZE                1021
#define IDC_TIME                        1022
#define IDC_CRC                         1023
#define IDC_TYPE                        1024
#define IDC_NAME                        1027
#define IDC_AMBIENTR                    1033
#define IDC_WHAT                        1035
#define IDC_AMBIENTG                    1036
#define IDC_AMBIENDB                    1037
#define IDC_AMBIENTA                    1038
#define IDC_DIFFUSER                    1039
#define IDC_DIFFUSEG                    1040
#define IDC_DIFFUSEB                    1041
#define IDC_DIFFUSEA                    1042
#define IDC_SPECULARR                   1043
#define IDC_SPECULARG                   1044
#define IDC_SPECULARB                   1045
#define IDC_SPECULARA                   1046
#define IDC_FILTERR                     1047
#define IDC_CUTOFF                      1047
#define IDC_FILTERG                     1048
#define IDC_FALLOFF                     1048
#define IDC_FILTERB                     1049
#define IDC_THETA                       1049
#define IDC_FILTERA                     1050
#define IDC_PHI                         1050
#define IDC_REFRACTIONR                 1051
#define IDC_REFRACTIONG                 1052
#define IDC_REFRACTIONB                 1053
#define IDC_REFRACTIONA                 1054
#define IDC_SHINESS                     1055
#define IDC_STRENGTH                    1056
#define IDC_ATTENUATION0                1056
#define IDC_ATTENUATION1                1057
#define IDC_FOCUS                       1057
#define IDC_ATTENUATION2                1058
#define IDC_LENSRX                      1058
#define IDC_SELFILLUMINATION            1059
#define IDC_ATTENUATION3                1059
#define IDC_LENSRY                      1059
#define IDC_OPACITY                     1060
#define IDC_BRIGHTNESS                  1060
#define IDC_STATICFRICTION              1061
#define IDC_CONTRAST                    1061
#define IDC_BOUNCE                      1062
#define IDC_BLACKPOINT                  1062
#define IDC_SLIDINGFRICTION             1063
#define IDC_VERTECES                    1063
#define IDC_WHITEPOINT                  1063
#define IDC_AMBIENT                     1064
#define IDC_VERTEXSIZE                  1064
#define IDC_GAMMA                       1064
#define IDC_DIFFUSE                     1065
#define IDC_VERTEXFLAGS                 1065
#define IDC_SPECULAR                    1066
#define IDC_INDECES                     1066
#define IDC_FILTER                      1067
#define IDC_INDEXSIZE                   1067
#define IDC_REFRACTION                  1068
#define IDC_INDEXFLAGS                  1068
#define IDC_SHINESSM                    1069
#define IDC_VERTEXLIST                  1069
#define IDC_STRENGTHM                   1070
#define IDC_INDEXLIST                   1070
#define IDC_ILLUMINATIONM               1071
#define IDC_MATERIALS                   1071
#define IDC_SUBSETS                     1071
#define IDC_OPACITYM                    1072
#define IDC_LIST                        1072
#define IDC_STATICFRICTIONM             1073
#define IDC_SLIDINGFRICTIONM            1074
#define IDC_HEX                         1074
#define IDC_BOUNCEM                     1075
#define IDC_FLOAT                       1075
#define IDC_BFLOAT                      1076
#define IDC_BHEX                        1077
#define IDC_COMX                        1079
#define IDC_COMY                        1080
#define IDC_COMZ                        1081
#define IDC_BUTTON13                    1082
#define IDC_BUTTON14                    1083
#define IDC_VBINDEX                     1085
#define IDC_IBINDEX                     1086
#define NUMVERTEX                       1087
#define IDC_NUMINDEX                    1088
#define IDC_MATERIAL                    1090
#define IDC_MAXVERTEX                   1091
#define IDC_MAXINDEX                    1092
#define IDC_EDIT1                       1092
#define IDC_EDIT2                       1093
#define IDC_EDIT3                       1094
#define IDC_EDIT4                       1095
#define IDC_EDIT5                       1096
#define IDC_EDIT6                       1097
#define IDC_EDIT7                       1098
#define IDC_EDIT8                       1099
#define IDC_EDIT9                       1100
#define IDC_EDIT10                      1101
#define IDC_EDIT11                      1102
#define IDC_EDIT12                      1103
#define IDC_EDIT13                      1104
#define IDC_EDIT14                      1105
#define IDC_EDIT15                      1106
#define IDC_EDIT16                      1107
#define IDC_AUTOSET                     1109
#define IDC_RICHEDIT1                   1110
#define IDC_RADIO1                      1111
#define IDC_RADIO2                      1112

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1112
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
